version: 0.0
os: linux
files:
 - source: /
   destination: /home/ubuntu/nodejs_blog
hooks:
 BeforeInstall:
  - location: before.sh
    timeout: 5
 AfterInstall:
  - location: build.sh
    timeout: 60
